### ISSUE TITLE
Add 6 more exercises to have 20 exercises

### ISSUE THREAD

**Issue by pclausen** [exercism/fortran#117]
# exercises to add

currently 14, target is to have 20. Following looks fairly easy to do with Fortran (few string operations)

- [ ] ~~Saddel point~~ Returns variable lenght list which is kind of painful...
- [ ] ~~Tree Building~~ Mssing tests in problem-specifications/exercises/tree-building
- [x] Triangle 
- [x] Queen Attack
- [ ] ~~Change~~ Harder than I thought...
- [x] Rational Numbers
- [x]  High Scores

Suggestions from @SaschaMann and Angelika Tyborska
- [ ] pascal's triangle,
- [ ] accumulate, 
- [ ] all-your-base, 
- [x] grains, 
- [ ] isbn-verifier (maybe), 
- [x] leap, 
- [ ] luhn (maybe), 
- [ ] ~~pythagorean-triplet~~  Tricky because returns variable lists
- [ ] ~~prime-factors~~  Tricky because returns variable lists
- [x] perfect-numbers, 
- [ ] sieve
- [ ] project euler 
- [x] space age, 
- [ ] bowling 
- [ ] sum of multiples
- [ ] clock 
- [ ] dnd character

**Comment by pclausen** [comment]
We have 20 exercises now, but I will leave this list open as a good place to start if one wants to create further eercises

**Comment by hiljusti** [comment]
Nice work!

Let me reserve `leap` (easy: integer comparison and boolean logic) and `accumulate` (harder: higher order functions)

**Comment by SaschaMann** [comment]
>  Tricky because returns variable lists

You don't have to stick to the canonical tests perfectly. For example, you could tell people to return a vector of length 10 and set unused results to 0 or -1, and avoid the problem of variable length lists.

**Comment by justaducky** [comment]
What about "Pig Latin?"

**Comment by ErikSchierboom** [comment]
There are 20+ exercises, so this can be closed.
