### ISSUE TITLE
Issues with matrix exercise

### ISSUE THREAD

**Issue by zmoon** [exercism/fortran#170]
There are some issues with the stub:
* `m` declaration doesn't have the dimension that it needs (`:`)
* the declared dimensions of the result (`r` or `c`) are wrong for both `row` and `column` (they should be switched as it stands)
* the `A` declaration is not needed

Also, I feel that the dims should be reversed in the argument/tests. Although Fortran uses column-major storage order, I think most people still think of the first dimension as the "rows" dimension if you have a two-dimensional array (matrix). [Wikipedia agrees](https://en.wikipedia.org/wiki/Row-_and_column-major_order):

> in Fortran, arrays are stored in column-major order, while the array indexes are still written row-first (colexicographical access order)

**Comment by pclausen** [comment]
@zmoon Thanks for reporting. I think I created this exercise and I honestly did not think about this. I will create a PR to change this and I would appreciate if you would review it.

**Comment by pclausen** [comment]
@zmoon I think the exercise should now be correct, but please double check.

**Comment by D3usXMachina** [comment]
I believe the README.md is misleading. [The instructions](https://github.com/exercism/fortran/blob/main/exercises/practice/matrix/.docs/instructions.md) say that the matrix is given as a string with embedded newlines. This is the case in other tracks that implement this exercise (lua, typescript, python and PHP). Here, however, the tests use an array of strings representing the rows instead.

**Comment by ErikSchierboom** [comment]
Closed by #175
