### ISSUE TITLE
Windows Build has several of the exercise tests failing

### ISSUE THREAD

**Issue by kotp** [exercism/fortran#188]
https://github.com/orgs/exercism/teams/fortran if you have some time, it might be worth taking a look at the Windows build, as it looks like several of the exercise tests are failing there.

**Comment by kotp** [comment]
For details of failing tests, see [github actions - runs].

[github actions - runs]: https://github.com/exercism/fortran/actions/runs/3290802070

**Comment by ErikSchierboom** [comment]
I'm removing the Windows build, as Windows does not seem to supported natively and Windows users can use WSL if they want (I am doing that myself).

**Comment by kotp** [comment]
> I'm removing the Windows build, as Windows does not seem to supported natively and Windows users can use WSL if they want (I am doing that myself).

Thank you @ErikSchierboom .
