### ISSUE TITLE
Consider consistency for the exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/fortran#2]
- Is there a style guide for Fortran?
- Are these styles encouraged or enforced?
- Are there any conventions that we should adopt on this track for the sake of consistency?
- Can we enforce these?
- Is there a linter? Are there many? Should we use one?
- When you add a linter, edit the pull request template [link]
- Update the pull request template with checks that are appropriate for this track
- Is there a common convention for filenames? If not, what should our convention be?

Note that this is about the exercises (the test suites and code examples), not people's solutions.

**Comment by sentientmonkey** [comment]
Still searching on linting for Fortran. There's nothing that I can tell that's inbuilt (other than the compiler itself), but there may be open source tools that can help here.

Style-wise, we'll likely stick to f90, free-form (vs. fixed), and a consistent spacing (probably 2 or 4 space indentation).

**Comment by kytrinyx** [comment]
If there's no particular suggested library / best practice, I tend to recommend sticking with whatever small set of rules that seem to make sense. Your style-wise list sounds like a totally reasonable place to start.

**Comment by zbeekman** [comment]
> Is there a style guide for Fortran?

No formalized or completely agreed upon convention. Some books have great suggestions though, like:

- @rouson's [Scientific Software Design: The Object Oriented Way](http://amzn.to/2s1B65R)
- [Modern Fortran](http://amzn.to/2tXUqT3)
- [Modern Fortran Explained](http://amzn.to/2s1NRNX) (This doesn't really have style recommendations, but it is the defacto language reference and teaching book)

We sort of have a living document/discussion about "Best practices" at Fortran F/OSS Programmers: https://github.com/Fortran-FOSS-Programmers/Best_Practices. Also, Stefano, AKA @szahgi has one at: https://github.com/szaghi/zen-of-fortran
Here's yet another style guide: https://github.com/kramer314/fortran-style-guide

> Are these styles encouraged or enforced?

Encourages... nothing is enforced. Tons of people still write in fixed format F77 😭 

> Are there any conventions that we should adopt on this track for the sake of consistency?

Modern, FREE form. I prefer 2 space indentation, but 4 is fine too. [JUST DON'T USE TABS](https://www.theregister.co.uk/2017/06/16/spaces_vs_tabs/) lol, no I'm not sure it matters, but I do need to go have a look at the standard again to see whether or not they are explicitly prohibited. I don't think they are but need to double check.

There are two tools that can do some  style manipulation:

- https://github.com/pseewald/fprettify
- https://github.com/wvermin/findent
- https://github.com/dev-zero/f90-formatter

I haven't used them much.

> Can we enforce these?

W/ GFortran you can get some style checking and linting with: `-std=f2008 -W -Wall -Wextra -pedantic`

> Is there a linter? Are there many? Should we use one?

There are no good Free linters that I know of. The only one I can find that seems somewhat reasonable is https://github.com/ratnania/fortlint

> Is there a common convention for filenames? If not, what should our convention be?

Standard is `.f90` for free format and `.f` for fixed (or `.F90` for files that need preprocessing, and `.F` for fixed files that need pre-processing. Unfortunately, however, there is not standardized pre-processor, so we should avoid all pre-processing.) Some people use `.f03` or `.f95` etc. but this enrages most other Fortran programmers.

**Comment by kytrinyx** [comment]
> Modern, FREE form.

It sounds like we should (if we can) enforce whatever minimal set of things that seem reasonable per modern, free form sensibilities here in the repository. For the people working through the track we should probably summarize what you wrote here: no broad consensus, some great suggestions, we recommend tending towards the modern style.
