### ISSUE TITLE
Create stub files for all exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/fortran#34]
We have decided to require all file-based tracks to provide stubs for their exercises.

The lack of stub file generates an unnecessary pain point within Exercism, contributing a significant proportion of support requests, making things more complex for our students, and hindering our ability to automatically run test-suites and provide automated analysis of solutions.

We believe that it’s essential to understand error messages, know how to use an IDE, and create files. However, getting this right as you’re just getting used to a language can be a frustrating distraction, as it can often require a lot of knowledge that tends to seep in over time. At the start, it can be challenging to google for all of these details: what file extension to use, what needs to be included, etc. Getting people up to speed with these things are not Exercism’s focus, and we’ve decided that we are better served by removing this source of confusion, letting people get on with actually solving the exercises.

The original discussion for this is at https://github.com/exercism/discussions/issues/238.

Therefore, we’d like this track to provide a stub file for each exercise.

- If this track already provides stub files for all exercises, please close this issue.
- If this track already has an open issue for creating stubs, then my apologies. Please close one as a duplicate.
- Otherwise, please respond to this issue with useful details about what needs to be done to complete this task in this track so that people who are not familiar with the track may easily contribute.

**Comment by pclausen** [comment]
I have the feeling the fortran exercism branch is quite stale at the moment. Who is maintaining exercism/fortran at the moment?

I could help out but I have near no experience with github. Let me know how I could help.

**Comment by kytrinyx** [comment]
@pclausen Ah, I'm not actually sure anyone _is_ maintaining the Fortran track right now... it tends to vary a bit. I would love your help here, if you're willing!

I think my first question is: are you familiar with the Fortran track on https://exercism.io? (If so, what have you done or seen there so far?)

**Comment by pclausen** [comment]
I created a pull request https://github.com/exercism/fortran/pull/30 almost a year ago which I think has stranded. I'm not new to exercism and think it would be good to have a working fortran track as well. I've never maintained a github repo but if you or someone else will help me with the git stuff I think I will be able to manage. I don't know how to ask to be a maintainer so I'm sorry if I am breaking some written or unwritten rules or conventions.

**Comment by kytrinyx** [comment]
You're not breaking any rules or conventions! Let me see if I can find you a "git buddy" to make sure you have a specific person available to ask for git help, and to get acquainted with all the githubby type questions and conventions. I'm going to try to get that done this week.

**Comment by kytrinyx** [comment]
@pclausen Alright, I've got one person with spare capacity right now to help out, and potentially some more in the not-too-distant future.

Are you a member of the Exercism Slack workspace? If not email me at katrina.owen@gmail.com and I can invite you in.
