### ISSUE TITLE
testlib missing 

### ISSUE THREAD

**Issue by funnell** [exercism/fortran#49]
Hello,

I thought I'd have a look at the Fortran track, and started the hello world program according to the instructions on the website:
`exercism download --exercise=hello-world --track=fortran`

Following the instructions in `hello_world_test.f90`, I get the following error:
```
❯ cmake ..
CMake Error at CMakeLists.txt:31 (file):
  file COPY cannot find
  "/Users/funnellt/Exercism/fortran/hello-world/../../testlib".


CMake Error at CMakeLists.txt:34 (add_subdirectory):
  add_subdirectory given source "testlib" which is not an existing directory.


-- Configuring incomplete, errors occurred!
See also "/Users/funnellt/Exercism/fortran/hello-world/Debug/CMakeFiles/CMakeOutput.log".
```

And `testlib` is of course no where to be found. I could try to fix this if someone points me in the right direction.

**Comment by SaschaMann** [comment]
Perhaps the make-file should check if testlib is available and if not, download it. I assume it's this directory: https://github.com/exercism/fortran/tree/master/testlib

**Comment by pclausen** [comment]
@funnell, 

thanks for the feedback. We are in the middle of a reconfiguring the Fortran track from [FUnit to use CMake](https://github.com/exercism/fortran/issues/29) and obviously it is not working as it should. But, I would be very grateful if you could help out as a tester(?)

I need a couple of days to figure out how the download stuff works with exercism and then hopefully fix this issue, but please expect this to be work in progress so the road may be bumpy.

**Comment by pclausen** [comment]
@funnell 

a work around for now is
```
cd exercise/hello-world
mkdir testlib
cd testlib
wget https://raw.githubusercontent.com/exercism/fortran/master/testlib/CMakeLists.txt
wget https://raw.githubusercontent.com/exercism/fortran/master/testlib/TesterMain.f90

```

**Comment by funnell** [comment]
Happy to help test. I'll wait until your pull request is merged.

**Comment by pclausen** [comment]
@funnell Should be fixed with https://github.com/exercism/fortran/pull/58 

Let us know how your testing goes and I will close the issue accordingly if everything works out well

**Comment by funnell** [comment]
I'm downloading with the `exercism` command, which seems to be downloading older versions of the exercise. Is there a cache I can clear, or do I need to wait a certain amount of time for some syncing to complete?

**Comment by pclausen** [comment]
yeah, have the same issue, not sure where the problem is...

**Comment by pclausen** [comment]
@funnell You have to submit a dummy solution, eg
`exercism submit hello-world.f90`

And click on the link which is output by the command above. 

In the browser you then get the button: Update Exercise to latest edition

![Screenshot at 2019-10-23 01-34-40](https://user-images.githubusercontent.com/616409/67343500-c0e7cf80-f535-11e9-8626-9e2ecd98f1b4.png)

Now, redownload the exercise
`exercism download  -t fortran -e hello-world.f90`

**Comment by funnell** [comment]
Thanks @pclausen, but when I click on the update button I get to a page that looks like this:
<img width="518" alt="The_page_you_were_looking_for_doesn_t_exist__404_" src="https://user-images.githubusercontent.com/381464/67351778-4f4f5780-f51c-11e9-8d08-cc74b32d45a8.png">

**Comment by kotp** [comment]
The site is having some problems at the moment... has been for at least an hour.  Let me confirm that someone is aware of this via Slack.

**Comment by funnell** [comment]
Tried again, and it's working now. Thanks!!

**Comment by kotp** [comment]
Thank you @funnell !
