### ISSUE TITLE
Logo needed

### ISSUE THREAD

**Issue by sentientmonkey** [exercism/fortran#5]
Fortran really doesn't have a logo as far as I can tell. I'd love to see something really cool that looks like a punchcard, but I'm not exactly super good at illustration. Would love help here, but if not we'll end up with a simple pink/black fixed width "f".

**Comment by sentientmonkey** [comment]
For inspiration - https://homepage.divms.uiowa.edu/~jones/cards/collection/fortran888157.jpg

**Comment by kytrinyx** [comment]
I'm terrible with graphical design, but I like the idea of the punchcard-inspired thing.

**Comment by zbeekman** [comment]
Guys, I would love it if we could ditch the notion of an ancient outdated Fortran. Did you check the weather today before you got dressed? If so then you've already used Fortran, and it's had a very real, immediate impact on your day to day life. I'll think about Modern takes on Fortran and try to leave inspiration here.

**Comment by kytrinyx** [comment]
@zbeekman I was thinking more about "has history" than is old, but you make an excellent point. Thank you.

**Comment by zbeekman** [comment]
Didn't mean to criticize or come off harsh, just trying to dispel myths and misconceptions about one of my favorite languages 😄 . It certainly does have a lot of history.

> I don't know what the language of the year 2000 will look like, but I know it will be called Fortran.

-Tony Hoare, a long, long time ago

**Comment by zbeekman** [comment]
Also, god help anyone who calls it "FORTRAN" to my face 😝 (modern accepted spelling is "Fortran")

**Comment by sentientmonkey** [comment]
I'm so happy we've found someone who knows Fortran to help! 😄 My motivations for starting this track are pretty self-serving - I have recently come in contact with some older Fortran (mostly 77), that has been relied on and used for quite some time. I want show that it's possible to test-drive and modernize these applications. This means I'm learning quite a bit as I'm implementing new exercises and both older and newer ways of doing things. I know there's quite a bit of modern Fortran in HPC, so it's still heavily used in those areas as well. I'm sure we can come up with something is both modern but gives a nod back to history.

That said, I'm also not super great at visual design/illustration, so I'm open to see what ideas people have.

**Comment by sentientmonkey** [comment]
I have already made the mistake of calling it "FORTRAN" - maybe this good advice to include in the about?

**Comment by pclausen** [comment]
I think we can close this issue because of https://github.com/exercism/meta/issues/46
