### ISSUE TITLE
Travis build broken

### ISSUE THREAD

**Issue by pclausen** [exercism/fortran#71]
https://travis-ci.org/pclausen/fortran/builds/658030086?utm_medium=notification&utm_source=email

Not quite sure what is going wrong here... Seems to be something more central to the travis script. Fortran files build and execute succesfully.

```
gzip: stdin: not in gzip format

tar: Child returned status 1

tar: Error is not recoverable: exiting now

The command "bin/fetch-configlet" exited with 2.

0.00s$ bin/configlet lint .

/home/travis/.travis/functions: line 109: bin/configlet: No such file or directory

The command "bin/configlet lint ." exited with 127.

```

**Comment by yawpitch** [comment]
Over in the Python repo we’re working on a Python-based drop-in replacement for the fetch-configlet script that will back off when the API endpoint is rate limited... I’m still not totally sure that’s the problem on the server end, but it should help.

Wait to see our experience once we’ve merged https://github.com/exercism/python/pull/2186... bit of that works we may want to replace the original bash script in all the tracks that use it.
